# Generated by Django 4.2.3 on 2023-09-21 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uersprofile',
            old_name='firname',
            new_name='firstname',
        ),
    ]
